name: Deploy Laravel to Shared Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo

    - name: Create .env file
      run: |
        cp .env.example .env

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader --no-progress

    - name: Generate key
      run: php artisan key:generate --force

    - name: Clear and Cache config
      run: |
        php artisan config:clear
        php artisan config:cache
        php artisan route:clear
        php artisan route:cache
        php artisan view:clear
        php artisan view:cache

    - name: Deploy to Shared Hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/successapp.doniaries.my.id/ #url
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/storage/framework/cache/**
          **/storage/framework/sessions/**
          **/storage/framework/views/**
          **/storage/logs/**
          **/tests/**
          **/.env*
          **/.editorconfig
          **/.styleci.yml
          **/phpunit.xml
          **/README.md
          **/.gitattributes
          **/.gitignore
          **/phpspec.yml
