name: Deploy Laravel to Shared Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo

    - name: Create .env file
      run: |
        cp .env.example .env

    # Root Folder (Laravel Core)
    - name: Deploy Laravel Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/successapp.doniaries.my.id/  # Tambahkan path lengkap
        dangerous-clean-slate: false # Jangan hapus file yang ada
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/storage/framework/cache/**
          **/storage/framework/sessions/**
          **/storage/framework/views/**
          **/storage/logs/**
          **/tests/**
          **/.env*
          **/.editorconfig
          **/.styleci.yml
          **/phpunit.xml
          **/README.md
          **/.gitattributes
          **/.gitignore
          **/phpspec.yml
          **/public/**

    # Deploy Public Folder
    - name: Deploy Public Directory
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/successapp.doniaries.my.id/public/  # Tambahkan path lengkap
        local-dir: ./public/
        dangerous-clean-slate: false

    # Create and Deploy Root .htaccess
    - name: Upload Root .htaccess
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/successapp.doniaries.my.id/  # Tambahkan path lengkap
        local-dir: ./.htaccess
        dangerous-clean-slate: false

    # Upload Setup Script
    - name: Upload Setup Script
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/successapp.doniaries.my.id/  # Tambahkan path lengkap
        local-dir: ./setup.php
        dangerous-clean-slate: false

    # Upload Updated Index
    - name: Upload Updated Index
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/successapp.doniaries.my.id/public/  # Tambahkan path lengkap
        local-dir: ./public/index.php
        dangerous-clean-slate: false
